// lessons.js — the position lessons.
// GENERATED by tools/lessons/emit.js — do not edit by hand.
//
// Each one was measured before it was written down: the answer is the move the engine found, and
// a position only appears here if that move beats the second-best by at least 6% of the win.
// `wp` is what the best move is worth, so a wrong answer can be priced rather than just refused.
(typeof window !== 'undefined' ? window : self).Lessons = { drills: [
  {
    "id": "keep-pace",
    "title": "Keep pace",
    "prompt": "Both pawns are marching up the middle and you are a step behind. What now?",
    "why": "Walling here costs you a move and buys almost nothing: the opponent simply walks round it, and you are the one who fell a step behind. In a race that is even, the walls are worth more later, when there is a path worth cutting.",
    "setup": "m74 m14 m64 m24 m54",
    "answer": "m34",
    "answerText": "e6",
    "gap": 13,
    "wp": 54.5
  },
  {
    "id": "answer-standard",
    "title": "Answering the Standard Opening",
    "prompt": "Your opponent has just played the Standard Opening wall beside you. Find the reply.",
    "why": "The wall beside your pawn only matters if you have to go round it. The answer is a wall of your own that makes THEIR detour longer than yours — the exchange is about which player ends up paying more steps, not about who placed a wall first.",
    "setup": "m74 m14 m64 m24 m54 m34 v54",
    "answer": "h43",
    "answerText": "d4h",
    "gap": 6,
    "wp": 62.2
  }
] };
