// openings.js — the named openings, and how the page recognises one being played.
// GENERATED by tools/openings/emit.js — do not edit by hand.
//
// Two sources, two shapes. Wikipedia publishes move sequences, so those are matched as a prefix
// of the game: play the moves and the name appears, and it stays until the line is left. The
// QuoridorStrategy channel publishes board codes, which carry a position and not an order, so
// those are matched on the position itself -- which is the better test anyway, because a game
// that transposes into a named opening really is that opening.
//
// Notation note: Wikipedia names a wall after the square nearest a1, which is NOT the anchor
// quoridor-ai.com uses. The sequences below were each played out on Detour's own board before
// being written here; under the wrong anchor seven of the eight are still legal, so the mistake
// does not announce itself.
(function () {
  var LIST = [
    {
      "name": "Standard Opening",
      "note": "Both pawns walk straight up the middle, then a vertical wall goes in beside the opponent. Mirrored plays e6v instead, symmetrical plays d6v.",
      "src": "w",
      "line": "m74 m14 m64 m24 m54 m34 v54",
      "notation": "e2 e8 e3 e7 e4 e6 e3v"
    },
    {
      "name": "Shiller Opening",
      "note": "Lengthen their route, keep yours short. The wall can sit on c3, d3, e3 or f3.",
      "src": "w",
      "line": "m74 m14 m64 m24 m54 m34 v52",
      "notation": "e2 e8 e3 e7 e4 e6 c3v"
    },
    {
      "name": "The Stonewall",
      "note": "A wall laid behind your own pawn, to push back an opponent who comes forward. It continues f2h, b2h, h2v.",
      "src": "w",
      "line": "m74 m14 m64 m24 h63",
      "notation": "e2 e8 e3 e7 d2h"
    },
    {
      "name": "Ala Opening",
      "note": "Keep one easy path for yourself while leaving the opponent choices. Also played as f5h, c4v or g4v.",
      "src": "w",
      "line": "m74 m14 m64 m24 m54 m34 h33",
      "notation": "e2 e8 e3 e7 e4 e6 d5h"
    },
    {
      "name": "Gap Opening",
      "note": "The mainline continuation of the standard walls. The anti-gap answer is b3h.",
      "src": "w",
      "line": "m74 m14 m64 m24 m54 m34 v54 v24 h26",
      "notation": "e2 e8 e3 e7 e4 e6 e3v e6v g6h"
    },
    {
      "name": "The Sidewall",
      "note": "A very early wall that forces the second player into wasted moves. The counter is c7h.",
      "src": "w",
      "line": "m74 m14 v13",
      "notation": "e2 e8 d7v"
    },
    {
      "name": "Shatranj Opening",
      "note": "A wall on the very first move, channelling your own route to the far rank. e1v does the same job.",
      "src": "w",
      "line": "v73",
      "notation": "d1v"
    },
    {
      "name": "Reed Opening",
      "note": "Two walls on the third row with a single gap left in the middle.",
      "src": "w",
      "line": "h52 h50 h55 h57",
      "notation": "c3h a3h f3h h3h"
    },
    {
      "name": "Merit Opener",
      "note": "White walks straight up to e5, right beside the black pawn. It hands Black a jump and the depth that comes with it, and buys White the initiative to shape the board first.",
      "src": "g",
      "line": "m74 m14 m64 m24 m54 m34 m44",
      "notation": "e2 e8 e3 e7 e4 e6 e5"
    },
    {
      "name": "Jackob Opener",
      "note": "Black's wall goes in FRONT of their own pawn, not behind it. It stands in the way of White's march as much as their own, so White cannot answer with a straight push without losing tempo.",
      "src": "g",
      "line": "m74 m14 m64 m24 m54 h24",
      "notation": "e2 e8 e3 e7 e4 e6h"
    },
    {
      "name": "The Bowl",
      "note": "Four walls make a cup around your own pawn: closed behind, walled on both flanks, open only forwards. Nothing can be dropped behind you, and the answer shown is a long wall across the third row.",
      "src": "d",
      "line": "m74 m14 m64 m24 m54 m34 h54 h14 h52 h12 v45 h16 v41",
      "notation": "e2 e8 e3 e7 e4 e6 e3h e7h c3h c7h f4v g7h b4v"
    },
    {
      "name": "Standard Copy",
      "note": "Black answers every move of White's in the mirror, walls included.",
      "src": "q",
      "pos": "2,4 5,3||5,4 3,4",
      "code": "j7EUwGwOwCQ"
    },
    {
      "name": "Fresh Prince Eric",
      "note": "The same march up the middle, with Black's wall set one file across.",
      "src": "q",
      "pos": "1,3 5,3||5,4 3,4",
      "code": "j7EUwHMPMCQ"
    },
    {
      "name": "Black Rush",
      "note": "Black spends the opening running rather than walling, and pays for it with a single wall placed late.",
      "src": "q",
      "pos": "|4,4|5,4 2,4",
      "code": "j7oAAXNwBw"
    },
    {
      "name": "Cool Story Bro",
      "note": "Black walls early and low, before either pawn has committed.",
      "src": "q",
      "pos": "5,4||6,4 1,4",
      "code": "i0MAFQNQBQ"
    },
    {
      "name": "X-Black",
      "note": "Black gives up tempo for two walls, crossing White's route in two places.",
      "src": "q",
      "pos": "1,2|4,4|5,4 1,4",
      "code": "j8MAHIXNwBw"
    }
  ];

  // A game action, in the same compact form the lines are stored in. Two shapes reach here: the
  // {type, orient, to} an action is submitted as, and the {k, o, r, c} the match records in
  // M.actions to keep saved games small. Reading only the first gave every token as
  // "undefinedundefinedundefined", so nothing ever matched while everything looked wired up.
  function tokenOf(a) {
    if (!a) return '';
    if (a.k === 1) return a.o + a.r + a.c;
    if (a.k === 0) return 'm' + a.r + a.c;
    if (a.type === 'wall') return a.orient + a.r + a.c;
    if (a.type === 'move') return 'm' + a.to.r + a.to.c;
    return '';
  }
  // The other direction: a stored token back into an action the board can apply. The lessons
  // walk a line by playing its tokens, and compare what the learner played against them.
  function actionOf(t) {
    if (!t) return null;
    var r = Number(t[1]), c = Number(t[2]);
    if (t[0] === 'm') return { type: 'move', to: { r: r, c: c } };
    return { type: 'wall', orient: t[0], r: r, c: c };
  }

  // Walls and pawns, order-independent: the signature of a position.
  function signature(s) {
    if (!s || !s.pawns) return '';
    var h = [], v = [], k;
    for (k of s.hWalls) h.push(k);
    for (k of s.vWalls) v.push(k);
    return h.sort().join(' ') + '|' + v.sort().join(' ') + '|' +
      s.pawns.map(function (p) { return p.r + ',' + p.c; }).join(' ');
  }

  // The deepest opening this game is in. A longer line wins over a shorter one, so the Gap
  // Opening is reported rather than the Standard Opening it grows out of.
  function match(actions, state) {
    var best = null, seq = (actions || []).map(tokenOf).join(' ');
    for (var i = 0; i < LIST.length; i++) {
      var o = LIST[i], depth = 0;
      if (o.line) {
        if (seq === o.line || seq.indexOf(o.line + ' ') === 0) depth = o.line.split(' ').length;
      } else if (state && o.pos === signature(state)) {
        depth = (actions || []).length;
      }
      if (depth && (!best || depth > best.depth)) best = { name: o.name, note: o.note, src: o.src, depth: depth, notation: o.notation, code: o.code };
    }
    return best;
  }

  (typeof window !== 'undefined' ? window : self).Openings = { list: LIST, match: match, signature: signature, tokenOf: tokenOf, actionOf: actionOf };
})();
