// Writes path/lessons.js.
//
// I supply the wording; the engine supplies the answer, the margin and the win probability the
// answer is worth. A drill whose best move does not beat the second by MIN_GAP is refused
// outright rather than shipped -- marking a learner wrong for choosing between two good moves
// would teach them to distrust the lesson, which is worse than having fewer lessons.
const fs = require('fs'), path = require('path');
global.window = {}; global.performance = { now: () => Number(process.hrtime.bigint()) / 1e6 };
const root = path.join(__dirname, '../..');
eval(fs.readFileSync(path.join(root, 'rules.js'), 'utf8'));
eval(fs.readFileSync(path.join(root, 'path/engine.js'), 'utf8'));
const R = window.Rules, E = window.Engine;
const B = require('../openings/build.js');
const DRILLS = require('./drills.js');
// Les idees ne sont pas mesurees: elles ne posent pas de question a laquelle un coup repond.
// Elles traversent ce fichier telles quelles, et c'est ideas.js qui en est la source.
const IDEAS = require('./ideas.js');

const NODES = Number(process.env.NODES || 1500000);
const MIN_GAP = Number(process.env.MIN_GAP || 6);
const tokOf = a => a.type === 'move' ? 'm' + a.to.r + a.to.c : a.orient + a.r + a.c;
const glen = a => a.type === 'move'
  ? String.fromCharCode(97 + a.to.c) + (9 - a.to.r)
  : String.fromCharCode(97 + a.c) + (8 - a.r) + a.orient;

const out = [], refused = [];
for (const d of DRILLS) {
  const s = R.createState({ size: 9, walls: 10, players: 2 });
  const setup = [];
  for (const t of (d.prefix || '').split(' ').filter(Boolean)) {
    const a = d.tokens ? window.__tok(t) : B.fromGlendenning(t);
    setup.push(tokOf(a));
    if (a.type === 'move') R.applyMove(s, a.to); else R.applyWall(s, a.orient, a.r, a.c);
  }
  E.clearTable();
  const pos = E.fromRules(s);
  const res = E.analyse(pos, { budgetMs: 1e9, maxNodes: NODES, maxDepth: 30, exactRoot: true });
  const ranked = (res.moves || []).slice().sort((x, y) => y.score - x.score);
  const gap = ranked[1] ? (E.evalToWinProb(ranked[0].score) - E.evalToWinProb(ranked[1].score)) * 100 : 100;
  const bestA = E.toAction(pos, ranked[0].move);
  if (gap < MIN_GAP) { refused.push(`${d.id}: marge ${gap.toFixed(1)}% < ${MIN_GAP}%`); continue; }
  if (d.expect && d.expect !== bestA.type) { refused.push(`${d.id}: le moteur veut un ${bestA.type}, la lecon annonce un ${d.expect}`); continue; }
  out.push({ id: d.id, title: d.title, prompt: d.prompt, why: d.why,
             setup: setup.join(' '), answer: tokOf(bestA), answerText: glen(bestA),
             gap: Number(gap.toFixed(1)), wp: Number((E.evalToWinProb(ranked[0].score) * 100).toFixed(1)) });
}

const js = `// lessons.js — the position lessons.
// GENERATED by tools/lessons/emit.js — do not edit by hand.
//
// Each one was measured before it was written down: the answer is the move the engine found, and
// a position only appears here if that move beats the second-best by at least ${MIN_GAP}% of the win.
// \`wp\` is what the best move is worth, so a wrong answer can be priced rather than just refused.
//
// The ideas below are the other half of the lessons: the plans and habits from the strategy guide.
// Nothing measures them, because no single move answers "price every wall by the steps it adds".
// They are read rather than solved, and they come from tools/lessons/ideas.js unchanged.
(typeof window !== 'undefined' ? window : self).Lessons = {
  drills: ${JSON.stringify(out, null, 2).split('\n').map((l, i) => i ? '  ' + l : l).join('\n')},
  ideas: ${JSON.stringify(IDEAS, null, 2).split('\n').map((l, i) => i ? '  ' + l : l).join('\n')},
};
`;
fs.writeFileSync(path.join(root, 'path/lessons.js'), js);
console.log('leçon               marge   reponse  vaut');
for (const o of out) console.log(o.id.padEnd(20) + String(o.gap + '%').padStart(6) + '   ' + o.answerText.padEnd(7) + '  ' + o.wp + '%');
if (refused.length) { console.log('\nrefusees :'); for (const r of refused) console.log('  ' + r); }
console.log(`\n${out.length} lecons mesurees + ${IDEAS.length} idees -> path/lessons.js`);
