// Emits path/openings.js: the named openings plus the matcher the page uses to recognise them.
const fs = require('fs'), path = require('path');
const B = require('./build.js'), D = require('./data.js');

const tok = a => (a.type === 'move' ? 'm' + a.to.r + a.to.c : a.orient + a.r + a.c);
const out = [];

for (const o of D.lines) {
  const toks = o.line.split(' ').map(B.fromGlendenning);
  B.playLine(o.line.split(' '));                       // throws unless every move is legal
  out.push({ name: o.name, note: o.note, src: 'w', line: toks.map(tok).join(' '), notation: o.line });
}
for (const o of D.codes) {
  const d = B.decodeCode(o.code);
  const s = B.L.startState(B.R);
  s.hWalls = new Set(d.hWalls.map(w => w.r + ',' + w.c));
  s.vWalls = new Set(d.vWalls.map(w => w.r + ',' + w.c));
  s.pawns = d.pawns.map(p => ({ ...p }));
  out.push({ name: o.name, note: o.note, src: 'q', pos: B.sig(s), code: o.code });
}

const js = `// openings.js — the named openings, and how the page recognises one being played.
// GENERATED by tools/openings/emit.js — do not edit by hand.
//
// Two sources, two shapes. Wikipedia publishes move sequences, so those are matched as a prefix
// of the game: play the moves and the name appears, and it stays until the line is left. The
// QuoridorStrategy channel publishes board codes, which carry a position and not an order, so
// those are matched on the position itself -- which is the better test anyway, because a game
// that transposes into a named opening really is that opening.
//
// Notation note: Wikipedia names a wall after the square nearest a1, which is NOT the anchor
// quoridor-ai.com uses. The sequences below were each played out on Detour's own board before
// being written here; under the wrong anchor seven of the eight are still legal, so the mistake
// does not announce itself.
(function () {
  var LIST = ${JSON.stringify(out, null, 2).split('\n').map((l, i) => i ? '  ' + l : l).join('\n')};

  // A game action, in the same compact form the lines are stored in. Two shapes reach here: the
  // {type, orient, to} an action is submitted as, and the {k, o, r, c} the match records in
  // M.actions to keep saved games small. Reading only the first gave every token as
  // "undefinedundefinedundefined", so nothing ever matched while everything looked wired up.
  function tokenOf(a) {
    if (!a) return '';
    if (a.k === 1) return a.o + a.r + a.c;
    if (a.k === 0) return 'm' + a.r + a.c;
    if (a.type === 'wall') return a.orient + a.r + a.c;
    if (a.type === 'move') return 'm' + a.to.r + a.to.c;
    return '';
  }
  // The other direction: a stored token back into an action the board can apply. The lessons
  // walk a line by playing its tokens, and compare what the learner played against them.
  function actionOf(t) {
    if (!t) return null;
    var r = Number(t[1]), c = Number(t[2]);
    if (t[0] === 'm') return { type: 'move', to: { r: r, c: c } };
    return { type: 'wall', orient: t[0], r: r, c: c };
  }

  // Walls and pawns, order-independent: the signature of a position.
  function signature(s) {
    if (!s || !s.pawns) return '';
    var h = [], v = [], k;
    for (k of s.hWalls) h.push(k);
    for (k of s.vWalls) v.push(k);
    return h.sort().join(' ') + '|' + v.sort().join(' ') + '|' +
      s.pawns.map(function (p) { return p.r + ',' + p.c; }).join(' ');
  }

  // The deepest opening this game is in. A longer line wins over a shorter one, so the Gap
  // Opening is reported rather than the Standard Opening it grows out of.
  function match(actions, state) {
    var best = null, seq = (actions || []).map(tokenOf).join(' ');
    for (var i = 0; i < LIST.length; i++) {
      var o = LIST[i], depth = 0;
      if (o.line) {
        if (seq === o.line || seq.indexOf(o.line + ' ') === 0) depth = o.line.split(' ').length;
      } else if (state && o.pos === signature(state)) {
        depth = (actions || []).length;
      }
      if (depth && (!best || depth > best.depth)) best = { name: o.name, note: o.note, src: o.src, depth: depth, notation: o.notation, code: o.code };
    }
    return best;
  }

  (typeof window !== 'undefined' ? window : self).Openings = { list: LIST, match: match, signature: signature, tokenOf: tokenOf, actionOf: actionOf };
})();
`;
const dest = path.resolve(__dirname, '../../path/openings.js');
fs.writeFileSync(dest, js);
console.log(`${out.length} ouvertures -> ${dest} (${js.length} octets)`);
