// tools/genbook.js — builds book.js, the opening book for the standard 9x9 game.
//
//   node tools/genbook.js [plies] [msPerPosition] [maxPositions] [expand]
//
// Walks the opening tree, searches each position properly, and records every move that is
// within a small win-probability margin of the best one. app.js labels those "Book move"
// instead of grading them, which is the honest thing to do: in a known opening there is
// usually more than one good move and calling the others inaccuracies would be wrong.
//
// Only the top few moves are expanded, so the tree stays small; positions are keyed by the
// engine's Zobrist hash, so transpositions collapse together automatically.
const fs = require('fs');
const path = require('path');

global.window = {};
global.performance = { now: () => Number(process.hrtime.bigint()) / 1e6 };
const root = path.join(__dirname, '..');
eval(fs.readFileSync(path.join(root, 'rules.js'), 'utf8'));
eval(fs.readFileSync(path.join(root, 'path/engine.js'), 'utf8'));   // moved into path/ with the rest of the engine
const R = window.Rules, E = window.Engine;

const PLIES = parseInt(process.argv[2] || '6', 10);
const MS = parseInt(process.argv[3] || '1200', 10);
const MAXPOS = parseInt(process.argv[4] || '400', 10);
const MARGIN = 0.02;   // within 2% win probability of the best move counts as book
// Combien de coups on suit plus loin. Reglable, et il faut le regler avec MAXPOS: walk() est en
// PROFONDEUR D'ABORD, donc un plafond atteint en cours de route laisse un livre de travers --
// la premiere branche fouillee a fond, les autres pas du tout. Mieux vaut un arbre complet et
// etroit qu'un arbre large tronque. A 6 demi-coups, EXPAND=3 fait au plus 729 positions et
// EXPAND=4 au plus 4096, moins les transpositions, qui sont nombreuses ici puisque l'ordre des
// murs commute.
const EXPAND = parseInt(process.argv[5] || '3', 10);

const book = {};
const seen = new Set();
let count = 0;

function walk(state, ply) {
  if (ply >= PLIES || count >= MAXPOS || state.winner !== null) return;
  const pos = E.fromRules(state);
  const key = pos.hashLo + ':' + pos.hashHi;
  if (seen.has(key)) return;
  seen.add(key);

  const res = E.analyse(pos, { budgetMs: MS, maxDepth: 24, exactRoot: true });
  if (res.best === E.MOVE_NONE) return;
  count++;

  const wpBest = E.evalToWinProb(res.score);
  const ranked = res.moves.slice().sort((a, b) => b.score - a.score);
  const good = ranked.filter(rm => wpBest - E.evalToWinProb(rm.score) <= MARGIN).map(rm => rm.move);
  book[key] = good;
  process.stdout.write(`\r  ply ${ply}  positions ${count}/${MAXPOS}  book moves here: ${good.length}   `);

  for (let i = 0; i < Math.min(EXPAND, ranked.length); i++) {
    const a = E.toAction(pos, ranked[i].move);
    const next = R.cloneState(state);
    next.hWalls = new Set(state.hWalls); next.vWalls = new Set(state.vWalls);
    if (a.type === 'move') R.applyMove(next, a.to); else R.applyWall(next, a.orient, a.r, a.c);
    walk(next, ply + 1);
    if (count >= MAXPOS) return;
  }
}

console.log(`building opening book: ${PLIES} plies, ${MS}ms/position, cap ${MAXPOS}`);
walk(R.createState({ rows: 9, cols: 9 }), 0);

const out = `// book.js — opening book for the standard 9x9 game.
// GENERATED by tools/genbook.js — do not edit by hand.
// ${count} positions, ${PLIES} plies deep, ${MS}ms of search each, moves within
// ${(MARGIN * 100).toFixed(0)}% win probability of best.
//
// Shipped as plain JS rather than JSON so the page still works from a file:// URL, where
// fetch() of a local file is blocked. Keys are the engine's Zobrist hash ("lo:hi").
window.OpeningBook = ${JSON.stringify(book)};
`;
fs.writeFileSync(path.join(root, 'path/book.js'), out);
console.log(`\n${count} positions -> book.js (${(out.length / 1024).toFixed(1)} KB)`);
